ERROR_POLICY = {
    "InsufficientBalanceError": {
        "group": "payment_wallet",
        "should_notify": True,
        "title": "Үлдэгдэл хүрэлцэхгүй байна",
        "body": "Таны үлдэгдэл хүрэлцэхгүй байна. Дансаа цэнэглээд дахин оролдоно уу.",
        "priority": "high",
        "type": "insufficient_balance",
    },
    "UnpaidError": {
        "group": "payment_wallet",
        "should_notify": True,
        "title": "Төлбөр амжилтгүй",
        "body": "Төлбөр амжилтгүй болсон байна. Дахин оролдоно уу.",
        "priority": "high",
        "type": "payment_failed",
    },
    "InvalidWalletError": {
        "group": "payment_wallet",
        "should_notify": True,
        "title": "Дансны алдаа",
        "body": "Таны дансны мэдээлэл буруу байна. Оператор руу холбогдоно уу.",
        "priority": "high",
        "type": "invalid_wallet",
    },
    "InvalidPaymentError": {
        "group": "payment_wallet",
        "should_notify": True,
        "title": "Төлбөрийн алдаа",
        "body": "Төлбөр хийх үед алдаа гарлаа. Дахин оролдоно уу.",
        "priority": "high",
        "type": "invalid_payment",
    },
    "ChargePointOfflineError": {
        "group": "charging_station",
        "should_notify": True,
        "title": "Цэнэглэгч ажиллахгүй байна",
        "body": "Цэнэглэж байх үед алдаа гарлаа. Оператор руу холбогдоно уу.",
        "priority": "high",
        "type": "chargepoint_offline",
    },
    "NotAvailableError": {
        "group": "charging_station",
        "should_notify": True,
        "title": "Цэнэглэгч боломжгүй",
        "body": "Сонгосон цэнэглэгч одоогоор ашиглах боломжгүй байна.",
        "priority": "high",
        "type": "charger_not_available",
    },
    "UnauthorizedError": {
        "group": "auth_access",
        "should_notify": False,
        "title": "Нэвтрэх эрхгүй",
        "body": "Дахин нэвтэрнэ үү.",
        "priority": "normal",
        "type": "unauthorized",
    },
    "InvalidCredentialsError": {
        "group": "auth_access",
        "should_notify": False,
        "title": "Нэвтрэх мэдээлэл буруу",
        "body": "Нэр эсвэл нууц үг буруу байна.",
        "priority": "normal",
        "type": "invalid_credentials",
    },
    "TooManyOTP": {
        "group": "validation_otp",
        "should_notify": True,
        "title": "OTP оролдлого хэтэрлээ",
        "body": "Та түр хүлээгээд дахин оролдоно уу.",
        "priority": "normal",
        "type": "too_many_otp",
    },
    "InvalidOTPError": {
        "group": "validation_otp",
        "should_notify": False,
        "title": "OTP буруу",
        "body": "OTP буруу эсвэл хугацаа нь дууссан байна.",
        "priority": "normal",
        "type": "invalid_otp",
    },
    "DuplicateEntityError": {
        "group": "conflict_business",
        "should_notify": False,
        "title": "Давхардсан мэдээлэл",
        "body": "Өмнө нь бүртгэгдсэн байна.",
        "priority": "low",
        "type": "duplicate_entity",
    },
}